import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';

const require=createRequire(import.meta.url);
const { chromium }=require('playwright');
const root=new URL('../',import.meta.url);
const visual=await readFile(new URL('pwa/projects-work-visualization-runtime.js',root),'utf8');

const snapshot={project_id:'project-1',state:'planned',goal:{id:'goal-1',title:'Launch project',objective:'Ship a verified launch'},p10_plan:{id:'plan-1',state:'RUNNING',tasks:[{id:'research',status:'COMPLETED'},{id:'publish',status:'WAITING_APPROVAL'}]},work_plan:{id:'plan-1:v2',version:2,readiness:'ready',status:'running',milestones:[{id:'m1',title:'Evidence',objective:'Verify launch inputs',work_order_ids:['plan-1:v2:research']},{id:'m2',title:'Release',objective:'Publish approved launch',work_order_ids:['plan-1:v2:publish']}],work_orders:[{id:'plan-1:v2:research',title:'Research launch',objective:'Collect verified inputs',worker_type:'research',status:'completed',dependencies:[],expected_output:'Verified brief',resource_scope:{metadata:{p10_task_id:'research',requested_tool:'web_search_browser'}}},{id:'plan-1:v2:publish',title:'Publish launch',objective:'Publish approved launch',worker_type:'communications',status:'waiting_approval',dependencies:['plan-1:v2:research'],expected_output:'Live publication',resource_scope:{metadata:{p10_task_id:'publish',requested_tool:'publish_content'}}}]},live_work:{state:'RUNNING'},evidence:{total:1,by_task:{research:[{id:'ev-1',subject:'Verified research',observation:'The research result was verified.',verification_state:'verified',provenance:'tool_verified',created_at:'2026-10-09T04:00:00Z'}],publish:[]}}};
const history={plans:[{source_p10_plan_id:'plan-1',versions:[{id:'plan-1:v1',version:1,status:'ready',summary:'Initial plan',created_at:'2026-10-09T03:30:00Z'},{id:'plan-1:v2',version:2,status:'running',summary:'Revised launch plan',created_at:'2026-10-09T03:45:00Z'}],deltas:[{id:'delta-1',reason:'Add approval before publish',created_at:'2026-10-09T03:46:00Z',items:[{action:'modify',task_id:'publish'}]}]}]};
const project={id:'project-1',name:'Canonical Project',goal:'Ship a verified launch',files:[{id:'file-1',title:'Launch brief',kind:'source'}],threads:[{id:'thread-1',title:'Release decision',pinned_reply_id:'reply-1',pinned_reply:{content:'Use the verified launch brief.'}}],activity:[{id:'act-1',action:'updated project',detail:'Launch target confirmed',actor:'owner',target_type:'project_brief',target_id:'project-1',created_at:'2026-10-09T03:20:00Z'}]};

const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#07101c;color:#eef5ff;font:14px system-ui}.project-btn{padding:8px 10px;border-radius:9px;border:1px solid #39516c;background:#101f33;color:#eef5ff}#host{max-width:1180px;margin:auto;padding:16px;box-sizing:border-box}</style></head><body><main id="host"></main><script>
window.prEsc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));window.projectCurrent=${JSON.stringify(project)};window.projectTab='status';window.__apiCalls=[];window.__snapshot=${JSON.stringify(snapshot)};window.__history=${JSON.stringify(history)};window.__vishnuCanonicalProjectWork={snapshotCache:new Map([['project-1',window.__snapshot]]),historyCache:new Map([['project-1',window.__history]])};window.refreshCanonicalProjectWork=async()=>[window.__snapshot,window.__history];window.api=async(path,options={})=>{window.__apiCalls.push({path,method:options.method||'GET'});if((options.method||'GET')!=='GET')throw new Error('Visualization attempted mutation');if(path.endsWith('/work'))return structuredClone(window.__snapshot);if(path.endsWith('/work/history'))return structuredClone(window.__history);throw new Error('Unhandled '+path)};window.showToast=()=>{};window.renderProjectDetail=()=>{const h=document.querySelector('#host');if(window.projectTab==='status')window.renderProjectStatus(h,window.projectCurrent);if(window.projectTab==='structure')window.renderProjectStructure(h,window.projectCurrent);if(window.projectTab==='activity')window.renderProjectActivity(h,window.projectCurrent)};window.renderProjectStatus=(h)=>h.textContent='legacy status';window.renderProjectStructure=(h)=>h.textContent='legacy structure';window.renderProjectActivity=(h)=>h.textContent='legacy activity';
</script><script src="/projects-work-visualization-runtime.js"></script></body></html>`;

const server=createServer((req,res)=>{if(req.url==='/projects-work-visualization-runtime.js'){res.writeHead(200,{'content-type':'application/javascript'});return res.end(visual)}res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(html)});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();const browser=await chromium.launch({headless:true});
try{
  for(const viewport of [{width:390,height:844,isMobile:true},{width:1440,height:1000,isMobile:false}]){
    const page=await browser.newPage({viewport,deviceScaleFactor:viewport.isMobile?2:1,isMobile:viewport.isMobile,hasTouch:viewport.isMobile});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${address.port}/`,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__vishnuCanonicalProjectVisualizations?.installed===true);

    await page.evaluate(()=>window.renderProjectStatus(document.querySelector('#host'),window.projectCurrent));await page.locator('.cv-status-stage').waitFor();let text=await page.locator('#host').innerText();assert.match(text,/3D status/i);assert.match(text,/Research launch/);assert.match(text,/Publish launch/);assert.match(text,/Waiting Approval/i);assert.match(text,/1 record\(s\)/i);

    await page.evaluate(()=>{window.projectTab='structure';window.renderProjectStructure(document.querySelector('#host'),window.projectCurrent)});await page.locator('.cv-graph').waitFor();text=await page.locator('#host').innerText();assert.match(text,/3D project structure/i);assert.match(text,/depends on/i);assert.match(text,/web_search_browser/i);assert.match(text,/Verified research/i);assert.match(text,/Launch brief/i);assert.match(text,/does not invent links/i);

    await page.evaluate(()=>{window.projectTab='activity';window.renderProjectActivity(document.querySelector('#host'),window.projectCurrent)});await page.locator('.cv-activity-list').waitFor();text=await page.locator('#host').innerText();assert.match(text,/WorkPlan v2/i);assert.match(text,/Add approval before publish/i);assert.match(text,/Evidence · Research launch/i);assert.match(text,/Launch target confirmed/i);assert.match(text,/No synthetic execution events/i);

    if(viewport.isMobile){const g=await page.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth,columns:getComputedStyle(document.querySelector('.cv-layout')).gridTemplateColumns}));assert.ok(g.scroll<=g.viewport+2,`visualization overflow: ${JSON.stringify(g)}`);assert.ok(!g.columns.includes(' '),`mobile layout must collapse: ${g.columns}`)}
    assert.equal(await page.evaluate(()=>window.__apiCalls.some(c=>c.method!=='GET')),false);assert.deepEqual(errors,[],`page errors: ${errors.join(' | ')}`);await page.close();
  }
} finally {await browser.close();await new Promise(resolve=>server.close(resolve))}
console.log('Canonical Project visualizations browser qualification passed.');
