import { readFile, writeFile, unlink } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const sourceUrl=new URL('./visualize_workspace_browser.mjs',import.meta.url);
const generatedUrl=new URL('./.visualize_workspace_browser.generated.mjs',import.meta.url);
let source=await readFile(sourceUrl,'utf8');

const injectBefore=`  await page.addStyleTag({path:'pwa/visualize-workspace.css'});\n  await page.addScriptTag({path:'pwa/visualize-workspace.js'});`;
const injectAfter=`  await page.addStyleTag({path:'pwa/visualize-workspace.css'});\n  await page.addStyleTag({path:'pwa/visualize-sources.css'});\n  await page.addStyleTag({path:'pwa/visualize-advanced.css'});\n  await page.addScriptTag({path:'pwa/visualize-workspace.js'});\n  await page.addScriptTag({path:'pwa/visualize-sources.js'});\n  await page.addScriptTag({path:'pwa/visualize-advanced.js'});`;
if(!source.includes(injectBefore))throw new Error('Visualize bundle injection contract changed; update runner explicitly.');
source=source.replace(injectBefore,injectAfter);

const closeBefore=`  await page.locator('#vzNavBackdrop').click({position:{x:600,y:300}}).catch(()=>page.evaluate(()=>document.querySelector('#vzNavBackdrop')?.click()));`;
const closeAfter=`  await page.evaluate(()=>document.querySelector('#vzNavBackdrop')?.click());`;
if(!source.includes(closeBefore))throw new Error('Visualize navigation close contract changed; update runner explicitly.');
source=source.replace(closeBefore,closeAfter);

const galleryBefore=`  await page.getByRole('button',{name:'Workflows'}).click();\n  assert.equal(await page.locator('.vz-gallery-card').count(),2,'Gallery category filters are functional');\n  await page.getByRole('button',{name:'All'}).click();`;
const galleryAfter=`  await page.locator('[data-vz-gallery-tab="Workflows"]').click();\n  assert.equal(await page.locator('.vz-gallery-card').count(),2,'Gallery category filters are functional');\n  await page.locator('[data-vz-gallery-tab="All"]').click();`;
if(!source.includes(galleryBefore))throw new Error('Visualize Gallery selector contract changed; update runner explicitly.');
source=source.replace(galleryBefore,galleryAfter);

const routeBefore=`    if(path.endsWith('/reach')&&method==='POST') {const input=JSON.parse(req.postData()||'{}');return json({origin:input.origin,direction:input.direction,node_ids:input.direction==='upstream'?['memory','agent','gateway']:['memory','knowledge','database','storage'],edge_ids:['e7','e9','e10'],max_hops:2});}`;
const routeAfter=`    if(path.endsWith('/edit')&&method==='POST') {const input=JSON.parse(req.postData()||'{}');return json({visualization:visual,receipt:{instruction:input.instruction,changed:true,operations:[{op:'move',node_id:'memory'}]}});}\n    if(path.endsWith('/presentation')&&method==='GET') return json({schema:'vishnu.visual.presentation.v1',title:visual.title,slides:[{id:'overview',title:'Overview',purpose:'Complete system overview',node_ids:graph.nodes.map(node=>node.id),edge_ids:graph.edges.map(edge=>edge.id)},{id:'memory',title:'Memory & Data',purpose:'Memory, knowledge and persisted data',node_ids:['agent','memory','knowledge','database','storage'],edge_ids:['e7','e9','e10','e13']}]});\n    if(path.endsWith('/scene')&&method==='GET') return json({schema:'vishnu.visual.scene.v1',dimension:'3d',title:visual.title,nodes:graph.nodes.map((node,index)=>({id:node.id,label:node.label,category:node.category,status:node.status,position:{x:100+(index%4)*210,y:90+Math.floor(index/4)*150,z:(index%5)*55},size:{width:node.width||160,height:node.height||56,depth:54},evidence_level:node.evidence_level,metadata:node.metadata||{}})),edges:graph.edges,metadata:{canonical_ids:true,projection_only:true}});\n    if(path.endsWith('/export')&&method==='GET') return route.fulfill({status:200,contentType:'application/octet-stream',body:'visual-export'});\n    if(path==='/iphone/api/visualizations/knowledge-map'&&method==='POST') return json({visualization:visual3});\n    if(path==='/iphone/api/visualizations/memory-map'&&method==='POST') return json({visualization:visual4});\n    if(path==='/iphone/api/visualizations/live-work-map'&&method==='POST') return json({visualization:visual2});\n${routeBefore}`;
if(!source.includes(routeBefore))throw new Error('Visualize API route fixture contract changed; update runner explicitly.');
source=source.replace(routeBefore,routeAfter);

const homeBefore=`  assert.equal(await page.locator('.vz-source-card').count(),5,'Desktop home must expose all five creation sources');`;
const homeAfter=`  assert.equal(await page.locator('.vz-source-card').count(),5,'Desktop home must expose all five creation sources');\n  assert.equal(await page.locator('.vza-native-create').count(),0,'Advanced maps must not change the frozen Visualize Home chrome');\n  await page.locator('#vzNew').click();\n  await page.waitForSelector('.vza-create-menu');\n  assert.equal(await page.locator('[data-vza-create]').count(),4,'Create Visual exposes Describe, Knowledge Map, Memory Map and Live Work without changing Home');\n  await page.locator('[data-vza-create="knowledge"]').click();\n  await page.waitForSelector('[data-vza-native]');\n  assert.match(await page.locator('.vza-dialog h2').innerText(),/Knowledge Map/,'Knowledge Map creation is a real advanced flow');\n  await page.locator('[data-vza-close]').click();`;
if(!source.includes(homeBefore))throw new Error('Visualize home assertion contract changed; update runner explicitly.');
source=source.replace(homeBefore,homeAfter);

const viewerBefore=`  await page.screenshot({path:\`${'${outputDir}'}/visualize-viewer-desktop.png\`,fullPage:false});`;
const viewerAfter=`  await page.screenshot({path:\`${'${outputDir}'}/visualize-viewer-desktop.png\`,fullPage:false});\n  assert.equal(await page.locator('[data-vza-edit]').count(),0,'Advanced tools must not add buttons to the frozen desktop viewer toolbar');\n  await page.locator('#vzMore').click();\n  await page.waitForSelector('[data-vza-menu-entry]');\n  await page.locator('[data-vza-menu-entry]').click();\n  await page.waitForSelector('.vza-create-menu');\n  assert.equal(await page.locator('[data-vza-action]').count(),4,'Desktop More menu exposes Edit, Presentation, 3D and Export');\n  await page.locator('[data-vza-action="edit"]').click();\n  await page.waitForSelector('[data-vza-edit-form]');\n  await page.locator('[data-vza-edit-form] textarea').fill('Move Memory Engine right 180');\n  await page.locator('[data-vza-edit-form] button[type="submit"]').click();\n  await page.waitForSelector('#vzViewer');\n  await page.locator('#vzMore').click();\n  await page.waitForSelector('[data-vza-menu-entry]');\n  await page.locator('[data-vza-menu-entry]').click();\n  await page.locator('[data-vza-action="present"]').click();\n  await page.waitForSelector('.vza-presentation');\n  assert.equal(await page.locator('[data-vza-count]').innerText(),'1 / 2','Presentation uses semantic slides from canonical graph IDs');\n  await page.locator('[data-vza-next]').click();\n  assert.match(await page.locator('[data-vza-slide-title]').innerText(),/Memory/,'Presentation next control changes semantic view');\n  await page.locator('[data-vza-close]').click();\n  await page.locator('#vzMore').click();\n  await page.waitForSelector('[data-vza-menu-entry]');\n  await page.locator('[data-vza-menu-entry]').click();\n  await page.locator('[data-vza-action="3d"]').click();\n  await page.waitForSelector('.vza-scene3d');\n  assert.match(await page.locator('.vza-scene3d footer').innerText(),/Shared canonical IDs/,'3D view is a projection of canonical IDs');\n  await page.locator('[data-vza-close]').click();\n  await page.locator('#vzExport').click();\n  await page.waitForSelector('.vza-export-grid');\n  assert.equal(await page.locator('[data-vza-export]').count(),6,'Export supports HTML, SVG, PNG, WebP, PDF and canonical JSON');\n  await page.locator('[data-vza-close]').click();`;
if(!source.includes(viewerBefore))throw new Error('Visualize desktop viewer screenshot contract changed; update runner explicitly.');
source=source.replace(viewerBefore,viewerAfter);

const contextualBefore=`  await page.evaluate(()=>window.__VISHNU_VISUALIZE__.openContextual());`;
const contextualAfter=`  await page.evaluate(()=>{window.__VISHNU_VISUALIZE__.selectNode('memory');window.__VISHNU_VISUALIZE__.openContextual();});`;
if(!source.includes(contextualBefore))throw new Error('Visualize contextual open contract changed; update runner explicitly.');
source=source.replace(contextualBefore,contextualAfter);

const pathBefore=`  await page.getByRole('button',{name:'Sources'}).click();\n  assert.ok(await page.locator('.vz-source-ref').count()>=3,'Sources tab renders authored node evidence');\n  await page.getByRole('button',{name:'Paths'}).click();\n  await page.getByRole('button',{name:'Show upstream'}).click();\n  await page.waitForSelector('.vz-reach-result');\n  await page.getByRole('button',{name:'Chat'}).click();`;
const pathAfter=`  await page.locator('#vzContextPanel [data-vz-context-tab="sources"]').click();\n  assert.ok(await page.locator('#vzContextPanel .vz-source-ref').count()>=3,'Sources tab renders authored node evidence');\n  await page.locator('#vzContextPanel [data-vz-context-tab="paths"]').click();\n  await page.locator('#vzContextPanel [data-vz-context-reach="upstream"]').click();\n  await page.waitForSelector('#vzContextPanel .vz-reach-result');\n  await page.waitForSelector('#vzContextPanel [data-vz-path-form]');\n  await page.locator('#vzContextPanel [data-vz-path-target]').selectOption('database');\n  await page.locator('#vzContextPanel [data-vz-path-form] button[type="submit"]').click();\n  await page.waitForSelector('#vzContextPanel .vz-path-result');\n  assert.match(await page.locator('#vzContextPanel .vz-path-result').innerText(),/Memory Engine.*Knowledge.*Database/s,'Paths tab renders the authored path returned by the API');\n  await page.locator('#vzContextPanel [data-vz-context-tab="chat"]').click();`;
if(!source.includes(pathBefore))throw new Error('Visualize contextual assertion contract changed; update runner explicitly.');
source=source.replace(pathBefore,pathAfter);

const mobileBefore=`  await mp.waitForSelector('#vzMobileNodeCard:not(.vz-hidden)');`;
const mobileAfter=`  await mp.waitForSelector('#vzMobileNodeCard:not(.vz-hidden)');\n  await mp.locator('#vzMore').click();\n  await mp.waitForSelector('[data-vza-menu-entry]');\n  await mp.locator('[data-vza-menu-entry]').click();\n  await mp.waitForSelector('.vza-create-menu');\n  assert.equal(await mp.locator('[data-vza-action]').count(),4,'Mobile viewer exposes Edit, Presentation, 3D and Export through its existing More menu');\n  await mp.locator('[data-vza-close]').click();`;
if(!source.includes(mobileBefore))throw new Error('Visualize mobile viewer contract changed; update runner explicitly.');
source=source.replace(mobileBefore,mobileAfter);

await writeFile(generatedUrl,source,'utf8');
try{await import(generatedUrl.href+'?run='+Date.now());}
finally{await unlink(fileURLToPath(generatedUrl)).catch(()=>{});}
