import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const {chromium}=require('playwright');const root=new URL('../',import.meta.url);const runtime=await readFile(new URL('pwa/work-attention-center.js',root),'utf8');
const items=[
{id:'a1',kind:'approval_required',severity:'urgent',title:'Needs your approval',reason:'Communications worker wants to publish externally.',authority:'approval_manager',action_type:'review_approval',deep_link:'/iphone/?section=approvals&approval=ap-1',project_name:'Marketing Launch',work_order_title:'Publish campaign',created_at:new Date(Date.now()-7200000).toISOString()},
{id:'r1',kind:'recovery_required',severity:'critical',title:'Recovery required',reason:'Email delivery outcome is uncertain. Do not resend until remote state is reconciled.',authority:'recovery_authority',action_type:'reconcile_recovery',deep_link:'/iphone/?project=p2&section=live',project_name:'Customer Update',work_order_title:'Send email'},
{id:'b1',kind:'blocked',severity:'attention',title:'Work blocked',reason:'Required capability is unavailable.',authority:'existing_p10_p6_runtime',action_type:'inspect_work',deep_link:'/iphone/?project=p3&section=live',project_name:'Website',work_order_title:'Deploy'},
{id:'v1',kind:'verification_failed',severity:'attention',title:'Evidence verification did not pass',reason:'Evidence was rejected.',authority:'evidence_store',action_type:'inspect_evidence',deep_link:'/iphone/?project=p4&section=work-plan',project_name:'Research',work_order_title:'Verify source'},
{id:'rv1',kind:'review_failed',severity:'review',title:'Plan review requires attention',reason:'Reviewer found a missing deliverable.',authority:'deterministic_reviewer',action_type:'inspect_plan',deep_link:'/iphone/?project=p5&section=work-plan',project_name:'Product',work_order_title:'Launch plan'},
{id:'c1',kind:'claim_unsupported',severity:'review',title:'Completion claim is not verified',reason:'Claim Gate rejected the completion claim.',authority:'claim_gate',action_type:'inspect_evidence',deep_link:'/iphone/?project=p6&section=work-plan',project_name:'API',work_order_title:'Confirm endpoint'}];
const snapshot={authority:'read_only_projection',counts:{total:6,approval:1,recovery:1,blocked:1,review:3,urgent:2},items};
const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#07101c;color:#eef5ff;font:14px system-ui}.gwa-head{display:flex;gap:10px}.gwa-panel{padding:20px}</style></head><body><section id="globalWorkPulse" class="gwa-panel"><div class="gwa-head"><strong>Vishnu work</strong></div></section><script src="/work-attention-center.js"></script></body></html>`;
let attentionReads=0;const server=createServer((req,res)=>{if(req.url==='/work-attention-center.js'){res.writeHead(200,{'content-type':'application/javascript'});return res.end(runtime)}if(req.url==='/iphone/api/work/attention?limit=200'){attentionReads+=1;res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify(snapshot))}res.writeHead(200,{'content-type':'text/html'});res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;const browser=await chromium.launch({headless:true});
try{for(const viewport of [{width:390,height:844,isMobile:true},{width:1440,height:1000,isMobile:false}]){const before=attentionReads;const page=await browser.newPage({viewport,deviceScaleFactor:viewport.isMobile?2:1,isMobile:viewport.isMobile,hasTouch:viewport.isMobile});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${port}/`,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__vishnuWorkAttentionCenter?.installed===true);await page.waitForFunction(()=>document.querySelector('[data-open-work-attention]'));await page.locator('[data-open-work-attention]').click();await page.locator('.wac-shell:not([hidden])').waitFor();await page.locator('.wac-card').first().waitFor();let text=await page.locator('.wac-panel').innerText();for(const expected of ['Attention Center','Approvals','Recovery','Blocked','Verification','Review','Claims','Marketing Launch','Publish campaign','Needs your approval','Approval Manager','2h ago','Review approval'])assert.match(text,new RegExp(expected,'i'),expected);assert.equal(await page.locator('[data-wac-filter]').count(),7);const expectedByFilter={approvals:'Needs your approval',recovery:'Recovery required',blocked:'Work blocked',verification:'Evidence verification did not pass',review:'Plan review requires attention',claims:'Completion claim is not verified'};for(const [filter,expected] of Object.entries(expectedByFilter)){await page.locator(`[data-wac-filter="${filter}"]`).click();text=await page.locator('.wac-scroll').innerText();assert.match(text,new RegExp(expected,'i'));}await page.locator('[data-wac-filter="all"]').click();assert.equal(await page.locator('.wac-card').count(),6);assert.equal(attentionReads-before,1,'Attention Center must issue one GET read per open');if(viewport.isMobile){const g=await page.evaluate(()=>({vw:innerWidth,scroll:document.documentElement.scrollWidth,panel:document.querySelector('.wac-panel').getBoundingClientRect().width,height:document.querySelector('.wac-panel').getBoundingClientRect().height,vh:innerHeight}));assert.ok(g.scroll<=g.vw+2,JSON.stringify(g));assert.ok(Math.abs(g.panel-g.vw)<3,JSON.stringify(g));assert.ok(Math.abs(g.height-g.vh)<3,JSON.stringify(g))}else{const w=await page.locator('.wac-panel').evaluate(el=>el.getBoundingClientRect().width);assert.ok(w>800&&w<=1040,`desktop Attention Center width ${w}`)}assert.deepEqual(errors,[],errors.join(' | '));await page.keyboard.press('Escape');assert.equal(await page.locator('.wac-shell').getAttribute('hidden'),'');await page.close()}}finally{await browser.close();await new Promise(r=>server.close(r))}console.log('Work Attention Center Chromium qualification passed.');