const $=id=>document.getElementById(id);const pages=[...document.querySelectorAll('.page')];const tabs=[...document.querySelectorAll('nav button')];
const state={origin:sessionStorage.getItem('pai.origin')||'',deviceId:sessionStorage.getItem('pai.deviceId')||'',deviceToken:sessionStorage.getItem('pai.deviceToken')||'',sessionToken:sessionStorage.getItem('pai.sessionToken')||'',expiresAt:Number(sessionStorage.getItem('pai.expiresAt')||0),eventsAbort:null};
function setStatus(text,ok=false){$('runtime-status').textContent=`● ${text}`;$('runtime-status').classList.toggle('offline',!ok)}
function applyRuntime(s={}){const stopped=!!s.emergency_stop||!!s.enabled&&s.event==='emergency.stop';setStatus(stopped?'Stopped':'Connected',!stopped);if(s.state){$('runtime-state').textContent=s.state;$('core-state').textContent=`Runtime ${s.state}`}if(stopped)$('core-state').textContent='Emergency stop active';$('device-state').textContent='Paired';$('security-state').textContent=stopped?'STOPPED':'Protected';$('session-state').textContent='Active';if(s.event==='approval.required'){$('approval-count').textContent='1';$('approval-copy').textContent=`${s.tool||'Action'} requires approval.`}if(s.event==='approval.approved'||s.event==='approval.rejected'){$('approval-count').textContent='0';$('approval-copy').textContent='No pending approvals.'}}
function normOrigin(v){return (v||'').trim().replace(/\/$/,'')}
function nonce(){const b=new Uint8Array(18);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
function headers(extra={}){return {'Content-Type':'application/json',...(state.sessionToken?{'Authorization':`Bearer ${state.sessionToken}`}:{}) ,...extra}}
async function call(path,opts={}){if(!state.origin)throw new Error('Runtime origin not configured');const r=await fetch(state.origin+path,{...opts,headers:{...headers(),...(opts.headers||{})}});let body={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||body.error||`HTTP ${r.status}`);return body}
async function ensureSession(){if(state.sessionToken&&Date.now()/1000<state.expiresAt-30)return true;if(!state.deviceId||!state.deviceToken)return false;const body=await call('/cloud/session',{method:'POST',body:JSON.stringify({device_id:state.deviceId,device_token:state.deviceToken})});state.sessionToken=body.session_token;state.expiresAt=body.expires_at;sessionStorage.setItem('pai.sessionToken',state.sessionToken);sessionStorage.setItem('pai.expiresAt',String(state.expiresAt));$('session-state').textContent='Active';startEvents();return true}
async function refreshStatus(){try{if(!await ensureSession()){setStatus('Unpaired');return}applyRuntime(await call('/cloud/status'))}catch(e){setStatus('Offline');$('runtime-state').textContent='Offline'}}
async function startEvents(){if(!state.origin||!state.sessionToken||state.eventsAbort)return;const ctrl=new AbortController();state.eventsAbort=ctrl;try{const r=await fetch(state.origin+'/cloud/events',{headers:{'Authorization':`Bearer ${state.sessionToken}`},signal:ctrl.signal});if(!r.ok||!r.body)throw new Error('event stream unavailable');const reader=r.body.getReader(),decoder=new TextDecoder();let buf='';while(true){const {value,done}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});let idx;while((idx=buf.indexOf('\n\n'))>=0){const frame=buf.slice(0,idx);buf=buf.slice(idx+2);const line=frame.split('\n').find(x=>x.startsWith('data: '));if(line){try{applyRuntime(JSON.parse(line.slice(6)))}catch{}}}}}catch(e){if(e.name!=='AbortError')setTimeout(()=>{state.eventsAbort=null;startEvents()},3000)}finally{if(state.eventsAbort===ctrl)state.eventsAbort=null}}
tabs.forEach(t=>t.addEventListener('click',()=>{tabs.forEach(x=>x.classList.toggle('active',x===t));pages.forEach(p=>p.classList.toggle('active',p.id===t.dataset.page));}));
$('runtime-origin').value=state.origin;
$('pair').addEventListener('submit',async e=>{e.preventDefault();const origin=normOrigin($('runtime-origin').value);const token=$('pair-token').value.trim();const code=$('pair-code').value.trim();if(!origin||!token||!code)return;$('pair-message').textContent='Pairing…';try{if(state.eventsAbort){state.eventsAbort.abort();state.eventsAbort=null}state.origin=origin;sessionStorage.setItem('pai.origin',origin);const r=await fetch(origin+'/pair/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,code,name:'iPhone Web Companion',platform:'web-ios'})});const body=await r.json();if(!r.ok)throw new Error(body.detail||'Pairing failed');state.deviceId=body.device.id;state.deviceToken=body.bearer_token;state.sessionToken='';sessionStorage.setItem('pai.deviceId',state.deviceId);sessionStorage.setItem('pai.deviceToken',state.deviceToken);sessionStorage.removeItem('pai.sessionToken');$('pair-token').value='';$('pair-code').value='';await ensureSession();$('pair-message').textContent='Paired securely for this browser session.';await refreshStatus()}catch(err){$('pair-message').textContent=err.message;setStatus('Pairing failed')}});
$('ask').addEventListener('submit',async e=>{e.preventDefault();const input=$('prompt');const text=input.value.trim();if(!text)return;input.value='';$('reply').hidden=false;$('reply').textContent='Thinking…';try{if(!await ensureSession())throw new Error('Pair a secure runtime first');const body=await call('/cloud/command',{method:'POST',body:JSON.stringify({text,nonce:nonce()})});if(body.approval_required){$('approval-count').textContent='1';$('approval-copy').textContent=`${body.tool} requires approval.`;$('reply').innerHTML=`<b>Approval required</b><p>${body.description||body.tool}</p><div class="row"><button class="action" id="approve-now">Approve once</button><button class="danger" id="reject-now">Reject</button></div>`;const decide=async decision=>{const x=await call('/cloud/approval',{method:'POST',body:JSON.stringify({approval_id:body.approval_id,decision,nonce:nonce()})});$('reply').textContent=x.reply||`Action ${decision}d.`;$('approval-count').textContent='0';$('approval-copy').textContent='No pending approvals.';};$('approve-now').onclick=()=>decide('approve').catch(x=>$('reply').textContent=x.message);$('reject-now').onclick=()=>decide('reject').catch(x=>$('reply').textContent=x.message)}else $('reply').textContent=body.reply||'Completed.'}catch(err){$('reply').textContent=err.message}});
$('memory-search').addEventListener('submit',async e=>{e.preventDefault();const q=$('memory-query').value.trim();try{if(!await ensureSession())throw new Error('Pair a secure runtime first');const body=await call('/cloud/memory/search',{method:'POST',body:JSON.stringify({query:q,include_sensitive:false})});$('memory-results').innerHTML='';if(!body.results.length){$('memory-results').textContent='No permitted memories found.';return}body.results.forEach(m=>{const p=document.createElement('p');const b=document.createElement('b');b.textContent=m.subject||m.type||'Memory';p.append(b,document.createElement('br'),document.createTextNode(m.content||''));$('memory-results').appendChild(p)})}catch(err){$('memory-results').textContent=err.message}});
async function emergency(enabled){const owner=$('owner-secret').value;try{if(!state.origin)throw new Error('Runtime origin not configured');const r=await fetch(state.origin+'/cloud/emergency-stop',{method:'POST',headers:{'Content-Type':'application/json','X-Personal-AI-Owner-Key':owner},body:JSON.stringify({enabled})});const body=await r.json();if(!r.ok)throw new Error(body.detail||body.error||'Emergency control failed');$('owner-secret').value='';await refreshStatus()}catch(err){$('owner-secret').value='';showDialog('Could not update emergency controls. Check your connection and owner secret, then try again.',false)}}
$('stop').addEventListener('click',()=>emergency(true));$('resume').addEventListener('click',async()=>{if(await showDialog('Resume governed tool actions? Existing permission and approval rules still apply.'))await emergency(false)});
refreshStatus();startEvents();setInterval(refreshStatus,60000);if('serviceWorker'in navigator){navigator.serviceWorker.register('/sw.js').catch(()=>{});}
function showDialog(message,confirmation=true){const dialog=$('companionDialog');if(dialog.open)return Promise.resolve(false);$('companionDialogMessage').textContent=message;dialog.querySelector('[value="cancel"]').hidden=!confirmation;dialog.querySelector('[value="continue"]').textContent=confirmation?'Continue':'Close';dialog.returnValue='';dialog.showModal();return new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue==='continue'),{once:true}))}
